ALTER TABLE users
  ADD COLUMN device_token VARCHAR(500) NULL,
  ADD COLUMN access_token VARCHAR(500) NULL,
  ADD COLUMN refresh_token VARCHAR(500) NULL,
  ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'user',
  ADD COLUMN profile_completed TINYINT(1) NOT NULL DEFAULT 0;